#TARGET = XCORE-AI-EXPLORER
#TARGET = XCORE-200-EXPLORER
TARGET = SOMANET-CoreC2X.xn
#TARGET = XK_VOICE_L71
APP_NAME = app_blink
#USED_MODULES = lib_xs3_math

COMMON_FLAGS = -Os -g -MMD -Wno-format -march=xs2a -report

XCORE_ARM_PROJECT = 0
VERBOSE = 0

XCC_FLAGS = $(COMMON_FLAGS)

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
